const LEVEL_1_GRID = [
  ['grass', 'grass', 'grass', 'rock', 'water', 'water', 'grass', 'grass'],
  ['grass', 'soil', 'soil', 'grass', 'rock', 'water', 'grass', 'grass'],
  ['grass', 'soil', 'soil', 'grass', 'grass', 'grass', 'grass', 'rock'],
  ['grass', 'grass', 'grass', 'grass', 'soil', 'soil', 'grass', 'grass'],
  ['water', 'water', 'rock', 'grass', 'soil', 'soil', 'grass', 'grass'],
  ['water', 'rock', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
  ['grass', 'grass', 'grass', 'soil', 'soil', 'rock', 'water', 'water'],
  ['grass', 'grass', 'grass', 'soil', 'soil', 'grass', 'water', 'rock'],
];

const LEVEL_2_GRID = [
  ['soil', 'soil', 'soil', 'grass', 'water', 'grass', 'grass', 'grass'],
  ['grass', 'grass', 'soil', 'grass', 'rock', 'grass', 'soil', 'grass'],
  ['grass', 'soil', 'soil', 'grass', 'grass', 'grass', 'soil', 'grass'],
  ['grass', 'grass', 'grass', 'rock', 'grass', 'soil', 'grass', 'grass'],
  ['water', 'water', 'grass', 'grass', 'soil', 'soil', 'grass', 'grass'],
  ['grass', 'rock', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
  ['grass', 'grass', 'grass', 'soil', 'soil', 'rock', 'water', 'water'],
  ['grass', 'grass', 'grass', 'soil', 'soil', 'grass', 'water', 'rock'],
];

const LEVEL_3_GRID = [
  ['soil', 'soil', 'grass', 'grass', 'water', 'water', 'grass', 'grass'],
  ['soil', 'soil', 'grass', 'grass', 'rock', 'water', 'grass', 'grass'],
  ['grass', 'soil', 'soil', 'grass', 'grass', 'grass', 'grass', 'rock'],
  ['grass', 'grass', 'grass', 'grass', 'soil', 'soil', 'grass', 'grass'],
  ['water', 'water', 'rock', 'grass', 'soil', 'soil', 'grass', 'grass'],
  ['water', 'rock', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
  ['grass', 'grass', 'grass', 'soil', 'soil', 'rock', 'water', 'water'],
  ['grass', 'grass', 'grass', 'soil', 'soil', 'grass', 'water', 'rock'],
];

const LEVEL_4_GRID = [
  ['soil', 'soil', 'soil', 'soil', 'soil', 'grass', 'grass', 'grass'],
  ['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
  ['grass', 'rock', 'grass', 'water', 'grass', 'grass', 'grass', 'grass'],
  ['grass', 'grass', 'grass', 'water', 'grass', 'soil', 'soil', 'grass'],
  ['water', 'water', 'grass', 'grass', 'grass', 'soil', 'soil', 'grass'],
  ['grass', 'rock', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
  ['grass', 'grass', 'grass', 'soil', 'soil', 'rock', 'water', 'water'],
  ['grass', 'grass', 'grass', 'soil', 'soil', 'grass', 'water', 'rock'],
];

export const LEVELS = [
  {
    id: 1,
    title: 'Level 1: First Steps',
    description: 'Move the robot to the target tile.',
    mission: 'Move the robot to the target tile.',
    learningGoal: 'A function is a command. Each block represents one function call.',
    pythonConcept: 'A function is a command. Each block represents one function call.',
    initialCoins: 20,
    grid: LEVEL_1_GRID,
    robotStart: { x: 0, y: 0 },
    robotDirection: 'east',
    target: { x: 2, y: 1 },
    unlockedBlocks: ['move', 'turn_left', 'turn_right'],
    winConditionType: 'reach_target',
    hint: 'Use move() and turn_right() in the correct order.',
    requiredBlocks: ['move()', 'turn_left()', 'turn_right()'],
  },
  {
    id: 2,
    title: 'Level 2: Plant Wheat',
    description: 'Plant wheat on three soil tiles.',
    mission: 'Plant wheat on three soil tiles.',
    learningGoal: 'Farming functions, command order, and function arguments.',
    pythonConcept: 'plant("wheat") represents calling a function with a value.',
    initialCoins: 20,
    grid: LEVEL_2_GRID,
    robotStart: { x: 0, y: 0 },
    robotDirection: 'east',
    target: { type: 'wheat', count: 3 },
    unlockedBlocks: ['move', 'turn_left', 'turn_right', 'plant_wheat'],
    winConditionType: 'plant_wheat',
    hint: 'Place plant("wheat") before move() when the robot is standing on soil.',
    requiredBlocks: ['move()', 'plant("wheat")'],
  },
  {
    id: 3,
    title: 'Level 3: Grow and Harvest Wheat',
    description: 'Grow and harvest two wheat crops.',
    mission: 'Grow and harvest two wheat crops.',
    learningGoal: 'Time-based state changes, wait, harvest, and crop growth duration.',
    pythonConcept: 'Objects can change state over time. Wheat becomes grown after 5 seconds.',
    initialCoins: 35,
    grid: LEVEL_3_GRID,
    robotStart: { x: 0, y: 0 },
    robotDirection: 'east',
    target: { type: 'wheat', count: 2 },
    unlockedBlocks: ['move', 'turn_left', 'turn_right', 'plant_wheat', 'wait', 'harvest'],
    winConditionType: 'harvest_wheat',
    hint: 'Wheat needs 5 seconds to become grown. Use wait(1) several times before harvest().',
    requiredBlocks: ['plant("wheat")', 'wait(1)', 'harvest()'],
  },
  {
    id: 4,
    title: 'Level 4: Repeat Automation',
    description: 'Plant carrot on a five-tile soil row.',
    mission: 'Plant carrot on five soil tiles.',
    learningGoal: 'Use a for loop to repeat a sequence of function calls.',
    pythonConcept: 'A for loop repeats the same block of code multiple times.',
    initialCoins: 50,
    grid: LEVEL_4_GRID,
    robotStart: { x: 0, y: 0 },
    robotDirection: 'east',
    target: { type: 'carrot', count: 5 },
    unlockedBlocks: ['move', 'turn_left', 'turn_right', 'plant_carrot', 'repeat_3', 'repeat_5'],
    winConditionType: 'plant_carrot',
    hint: 'Use Repeat 5 with plant_carrot() and move().',
    requiredBlocks: ['for i in range(5):', 'plant("carrot")', 'move()'],
  },
];
