const LEVEL_1_GRID = [
  ['grass', 'grass', 'grass', 'rock', 'water', 'water', 'grass', 'grass'],
  ['grass', 'soil', 'soil', 'grass', 'rock', 'water', 'grass', 'grass'],
  ['grass', 'soil', 'soil', 'grass', 'grass', 'grass', 'grass', 'rock'],
  ['grass', 'grass', 'grass', 'grass', 'soil', 'soil', 'grass', 'grass'],
  ['water', 'water', 'rock', 'grass', 'soil', 'soil', 'grass', 'grass'],
  ['water', 'rock', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
  ['grass', 'grass', 'grass', 'soil', 'soil', 'rock', 'water', 'water'],
  ['grass', 'grass', 'grass', 'soil', 'soil', 'grass', 'water', 'rock'],
];

const LEVEL_2_GRID = [
  ['soil', 'soil', 'soil', 'grass', 'water', 'grass', 'grass', 'grass'],
  ['grass', 'grass', 'soil', 'grass', 'rock', 'grass', 'soil', 'grass'],
  ['grass', 'soil', 'soil', 'grass', 'grass', 'grass', 'soil', 'grass'],
  ['grass', 'grass', 'grass', 'rock', 'grass', 'soil', 'grass', 'grass'],
  ['water', 'water', 'grass', 'grass', 'soil', 'soil', 'grass', 'grass'],
  ['grass', 'rock', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
  ['grass', 'grass', 'grass', 'soil', 'soil', 'rock', 'water', 'water'],
  ['grass', 'grass', 'grass', 'soil', 'soil', 'grass', 'water', 'rock'],
];

const LEVEL_3_GRID = [
  ['soil', 'soil', 'grass', 'grass', 'water', 'water', 'grass', 'grass'],
  ['soil', 'soil', 'grass', 'grass', 'rock', 'water', 'grass', 'grass'],
  ['grass', 'soil', 'soil', 'grass', 'grass', 'grass', 'grass', 'rock'],
  ['grass', 'grass', 'grass', 'grass', 'soil', 'soil', 'grass', 'grass'],
  ['water', 'water', 'rock', 'grass', 'soil', 'soil', 'grass', 'grass'],
  ['water', 'rock', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
  ['grass', 'grass', 'grass', 'soil', 'soil', 'rock', 'water', 'water'],
  ['grass', 'grass', 'grass', 'soil', 'soil', 'grass', 'water', 'rock'],
];

const LEVEL_4_GRID = [
  ['soil', 'soil', 'soil', 'soil', 'soil', 'grass', 'grass', 'grass'],
  ['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
  ['grass', 'rock', 'grass', 'water', 'grass', 'grass', 'grass', 'grass'],
  ['grass', 'grass', 'grass', 'water', 'grass', 'soil', 'soil', 'grass'],
  ['water', 'water', 'grass', 'grass', 'grass', 'soil', 'soil', 'grass'],
  ['grass', 'rock', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
  ['grass', 'grass', 'grass', 'soil', 'soil', 'rock', 'water', 'water'],
  ['grass', 'grass', 'grass', 'soil', 'soil', 'grass', 'water', 'rock'],
];

const LEVEL_5_GRID = [
  ['soil', 'grass', 'soil', 'grass', 'soil', 'grass', 'grass', 'grass'],
  ['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
  ['grass', 'rock', 'grass', 'water', 'grass', 'grass', 'grass', 'grass'],
  ['grass', 'grass', 'grass', 'water', 'grass', 'soil', 'soil', 'grass'],
  ['water', 'water', 'grass', 'grass', 'grass', 'soil', 'soil', 'grass'],
  ['grass', 'rock', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
  ['grass', 'grass', 'grass', 'soil', 'soil', 'rock', 'water', 'water'],
  ['grass', 'grass', 'grass', 'soil', 'soil', 'grass', 'water', 'rock'],
];

const LEVEL_6_GRID = [
  ['soil', 'soil', 'soil', 'soil', 'soil', 'water', 'rock', 'grass'],
  ['grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
  ['grass', 'rock', 'grass', 'water', 'grass', 'grass', 'grass', 'grass'],
  ['grass', 'grass', 'grass', 'water', 'grass', 'soil', 'soil', 'grass'],
  ['water', 'water', 'grass', 'grass', 'grass', 'soil', 'soil', 'grass'],
  ['grass', 'rock', 'grass', 'grass', 'grass', 'grass', 'grass', 'grass'],
  ['grass', 'grass', 'grass', 'soil', 'soil', 'rock', 'water', 'water'],
  ['grass', 'grass', 'grass', 'soil', 'soil', 'grass', 'water', 'rock'],
];

export const LEVELS = [
  {
    id: 1,
    title: 'Level 1: First Steps',
    description: 'Move the robot to the target tile.',
    mission: 'Move the robot to the target tile.',
    learningGoal: 'A function is a command. Each block represents one function call.',
    pythonConcept: 'A function is a command. Each block represents one function call.',
    initialCoins: 20,
    grid: LEVEL_1_GRID,
    robotStart: { x: 0, y: 0 },
    robotDirection: 'east',
    target: { x: 2, y: 1 },
    unlockedBlocks: ['move', 'turn_left', 'turn_right'],
    winConditionType: 'reach_target',
    hint: 'Use move() and turn_right() in the correct order.',
    requiredBlocks: ['move()', 'turn_left()', 'turn_right()'],
  },
  {
    id: 2,
    title: 'Level 2: Plant Wheat',
    description: 'Plant wheat on three soil tiles.',
    mission: 'Plant wheat on three soil tiles.',
    learningGoal: 'Farming functions, command order, and function arguments.',
    pythonConcept: 'plant("wheat") represents calling a function with a value.',
    initialCoins: 20,
    grid: LEVEL_2_GRID,
    robotStart: { x: 0, y: 0 },
    robotDirection: 'east',
    target: { type: 'wheat', count: 3 },
    unlockedBlocks: ['move', 'turn_left', 'turn_right', 'plant_wheat'],
    winConditionType: 'plant_wheat',
    hint: 'Place plant("wheat") before move() when the robot is standing on soil.',
    requiredBlocks: ['move()', 'plant("wheat")'],
  },
  {
    id: 3,
    title: 'Level 3: Grow and Harvest Wheat',
    description: 'Grow and harvest two wheat crops.',
    mission: 'Grow and harvest two wheat crops.',
    learningGoal: 'Time-based state changes, wait, harvest, and crop growth duration.',
    pythonConcept: 'Objects can change state over time. Wheat becomes grown after 5 seconds.',
    initialCoins: 35,
    grid: LEVEL_3_GRID,
    robotStart: { x: 0, y: 0 },
    robotDirection: 'east',
    target: { type: 'wheat', count: 2 },
    unlockedBlocks: ['move', 'turn_left', 'turn_right', 'plant_wheat', 'wait', 'harvest'],
    winConditionType: 'harvest_wheat',
    hint: 'Wheat needs 5 seconds to become grown. Use wait(1) several times before harvest().',
    requiredBlocks: ['plant("wheat")', 'wait(1)', 'harvest()'],
  },
  {
    id: 4,
    title: 'Level 4: Repeat Automation',
    description: 'Plant carrot on a five-tile soil row.',
    mission: 'Plant carrot on five soil tiles.',
    learningGoal: 'Use a for loop to repeat a sequence of function calls.',
    pythonConcept: 'A for loop repeats the same block of code multiple times.',
    initialCoins: 50,
    grid: LEVEL_4_GRID,
    robotStart: { x: 0, y: 0 },
    robotDirection: 'east',
    target: { type: 'carrot', count: 5 },
    unlockedBlocks: ['move', 'turn_left', 'turn_right', 'plant_carrot', 'repeat_3', 'repeat_5'],
    winConditionType: 'plant_carrot',
    hint: 'Use Repeat 5 with plant_carrot() and move().',
    requiredBlocks: ['for i in range(5):', 'plant("carrot")', 'move()'],
  },
  {
    id: 5,
    title: 'Level 5: Smart Farming',
    description: 'Plant carrot only on soil in a mixed row.',
    mission: 'Plant carrot only on soil tiles in the mixed row.',
    learningGoal: 'Use an if statement to run code only when a condition is true.',
    pythonConcept: 'An if statement checks a condition before running its child code.',
    initialCoins: 80,
    grid: LEVEL_5_GRID,
    robotStart: { x: 0, y: 0 },
    robotDirection: 'east',
    target: {
      cells: [
        { x: 0, y: 0, tileType: 'soil', cropType: 'carrot' },
        { x: 1, y: 0, tileType: 'soil', cropType: 'carrot' },
        { x: 2, y: 0, tileType: 'soil', cropType: 'carrot' },
        { x: 3, y: 0, tileType: 'soil', cropType: 'carrot' },
        { x: 4, y: 0, tileType: 'soil', cropType: 'carrot' },
      ],
    },
    unlockedBlocks: ['move', 'turn_left', 'turn_right', 'plant_carrot', 'repeat_5', 'if_on_soil'],
    winConditionType: 'smart_carrot_row',
    hint: 'Put plant_carrot() inside if_on_soil, then move forward each turn.',
    requiredBlocks: ['for i in range(5):', 'if on_soil():', 'plant("carrot")', 'move()'],
  },
  {
    id: 6,
    title: 'Level 6: Harvest Algorithm',
    description: 'Harvest grown crops while checking conditions before acting.',
    mission: 'Harvest all grown carrot crops.',
    learningGoal: 'Combine conditions, loops, and algorithmic thinking.',
    pythonConcept: 'Conditions and loops work together to make an algorithm adapt to state.',
    initialCoins: 100,
    grid: LEVEL_6_GRID,
    robotStart: { x: 0, y: 0 },
    robotDirection: 'east',
    target: {
      cropPositions: [
        { x: 0, y: 0 },
        { x: 1, y: 0 },
        { x: 2, y: 0 },
        { x: 3, y: 0 },
        { x: 4, y: 0 },
      ],
    },
    initialCrops: [
      { x: 0, y: 0, type: 'carrot', stage: 'grown' },
      { x: 1, y: 0, type: 'carrot', stage: 'grown' },
      { x: 2, y: 0, type: 'carrot', stage: 'grown' },
      { x: 3, y: 0, type: 'carrot', stage: 'grown' },
      { x: 4, y: 0, type: 'carrot', stage: 'grown' },
    ],
    unlockedBlocks: ['move', 'turn_left', 'turn_right', 'water', 'harvest', 'repeat_5', 'if_front_clear', 'if_crop_ready'],
    winConditionType: 'harvest_all_target_crops',
    hint: 'Use if_crop_ready to harvest only when a crop is ready. Use if_front_clear before moving.',
    requiredBlocks: ['for i in range(5):', 'if crop_ready():', 'harvest()', 'if front_clear():', 'move()'],
  },
];
