export const BLOCK_DEFINITIONS = [
  {
    id: 'move',
    name: 'Move',
    category: 'Movement',
    cost: 0,
    description: 'Move the robot one tile forward.',
    codePreview: 'move()',
    commandType: 'move',
  },
  {
    id: 'turn_left',
    name: 'Turn Left',
    category: 'Movement',
    cost: 0,
    description: 'Rotate the robot 90 degrees to the left.',
    codePreview: 'turn_left()',
    commandType: 'turn_left',
  },
  {
    id: 'turn_right',
    name: 'Turn Right',
    category: 'Movement',
    cost: 0,
    description: 'Rotate the robot 90 degrees to the right.',
    codePreview: 'turn_right()',
    commandType: 'turn_right',
  },
  {
    id: 'wait',
    name: 'Wait',
    category: 'Utility',
    cost: 5,
    description: 'Wait for 1 second. Crops keep growing while waiting.',
    codePreview: 'wait(1)',
    commandType: 'wait',
  },
  {
    id: 'plant_wheat',
    name: 'Plant Wheat',
    category: 'Farming',
    cost: 5,
    description: 'Plant wheat on the current soil tile.',
    codePreview: 'plant("wheat")',
    commandType: 'plant_wheat',
  },
  {
    id: 'plant_carrot',
    name: 'Plant Carrot',
    category: 'Farming',
    cost: 5,
    description: 'Plant carrot on the current soil tile.',
    codePreview: 'plant("carrot")',
    commandType: 'plant_carrot',
  },
  {
    id: 'harvest',
    name: 'Harvest',
    category: 'Farming',
    cost: 6,
    description: 'Harvest a fully grown crop.',
    codePreview: 'harvest()',
    commandType: 'harvest',
  },
  {
    id: 'water',
    name: 'Water',
    category: 'Farming',
    cost: 0,
    description: 'Water the current tile. Crop growth remains time-based.',
    codePreview: 'water()',
    commandType: 'water',
  },
  {
    id: 'repeat_5',
    name: 'Repeat 5',
    category: 'Control',
    cost: 30,
    description: 'Run child blocks five times.',
    codePreview: 'for i in range(5):',
    commandType: 'repeat',
    repeatCount: 5,
    hasChildren: true,
  },
  {
    id: 'if_crop_ready',
    name: 'If Crop Ready',
    category: 'Control',
    cost: 25,
    description: 'Run child blocks only when the crop here is grown.',
    codePreview: 'if crop_ready():',
    commandType: 'if',
    hasChildren: true,
    conditionType: 'crop_ready',
  },
];

export const FREE_BLOCK_IDS = ['move', 'turn_left', 'turn_right'];

export function getBlockDefinition(blockId) {
  return BLOCK_DEFINITIONS.find((block) => block.id === blockId);
}
