export const BLOCK_DEFINITIONS = [
  {
    id: 'move',
    name: 'Move',
    category: 'Movement',
    cost: 0,
    description: 'ë¡œë´‡??ë°”ë¼ë³´ëŠ” ë°©í–¥?¼ë¡œ ??ì¹??´ë™?©ë‹ˆ??',
    codePreview: 'move()',
    commandType: 'move',
  },
  {
    id: 'turn_left',
    name: 'Turn Left',
    category: 'Movement',
    cost: 0,
    description: 'ë¡œë´‡???¼ìª½?¼ë¡œ 90???Œì „?©ë‹ˆ??',
    codePreview: 'turn_left()',
    commandType: 'turn_left',
  },
  {
    id: 'turn_right',
    name: 'Turn Right',
    category: 'Movement',
    cost: 0,
    description: 'ë¡œë´‡???¤ë¥¸ìª½ìœ¼ë¡?90???Œì „?©ë‹ˆ??',
    codePreview: 'turn_right()',
    commandType: 'turn_right',
  },
  {
    id: 'wait',
    name: 'Wait',
    category: 'Utility',
    cost: 5,
    description: '1ì´??™ì•ˆ ê¸°ë‹¤ë¦½ë‹ˆ?? ê¸°ë‹¤ë¦¬ëŠ” ?™ì•ˆ ?‘ë¬¼?€ ê³„ì† ?ëž?ˆë‹¤.',
    codePreview: 'wait(1)',
    commandType: 'wait',
  },
  {
    id: 'plant_wheat',
    name: 'Plant Wheat',
    category: 'Farming',
    cost: 5,
    description: '?„ìž¬ ì¹¸ì— ë°€???¬ìŠµ?ˆë‹¤.',
    codePreview: 'plant("wheat")',
    commandType: 'plant_wheat',
  },
  {
    id: 'harvest',
    name: 'Harvest',
    category: 'Farming',
    cost: 6,
    description: '???ë? ?‘ë¬¼???˜í™•?©ë‹ˆ??',
    codePreview: 'harvest()',
    commandType: 'harvest',
  },
  {
    id: 'water',
    name: 'Water',
    category: 'Farming',
    cost: 0,
    description: '?„ìž¬ ì¹¸ì— ë¬¼ì„ ì¤ë‹ˆ?? ?‘ë¬¼ ?±ìž¥?€ ?œê°„ ê¸°ì??¼ë¡œ ì§„í–‰?©ë‹ˆ??',
    codePreview: 'water()',
    commandType: 'water',
  },
  {
    id: 'repeat_5',
    name: 'Repeat 5',
    category: 'Control',
    cost: 30,
    description: '?ˆìª½ ë¸”ë¡??5ë²?ë°˜ë³µ ?¤í–‰?©ë‹ˆ??',
    codePreview: 'for i in range(5):',
    commandType: 'repeat',
    repeatCount: 5,
    hasChildren: true,
  },
  {
    id: 'if_crop_ready',
    name: 'If Crop Ready',
    category: 'Control',
    cost: 25,
    description: '?„ìž¬ ì¹¸ì˜ ?‘ë¬¼?????ëž???Œë§Œ ?ˆìª½ ë¸”ë¡???¤í–‰?©ë‹ˆ??',
    codePreview: 'if crop_ready():',
    commandType: 'if',
    hasChildren: true,
    conditionType: 'crop_ready',
  },
];

export const FREE_BLOCK_IDS = ['move', 'turn_left', 'turn_right'];

export function getBlockDefinition(blockId) {
  return BLOCK_DEFINITIONS.find((block) => block.id === blockId);
}
