export const BLOCK_DEFINITIONS = [
  {
    id: 'move',
    name: 'Move',
    category: 'Movement',
    cost: 0,
    description: '드론이 바라보는 방향으로 한 칸 이동합니다.',
    codePreview: 'move()',
    commandType: 'move',
  },
  {
    id: 'turn_left',
    name: 'Turn Left',
    category: 'Movement',
    cost: 0,
    description: '드론이 왼쪽으로 90도 회전합니다.',
    codePreview: 'turn_left()',
    commandType: 'turn_left',
  },
  {
    id: 'turn_right',
    name: 'Turn Right',
    category: 'Movement',
    cost: 0,
    description: '드론이 오른쪽으로 90도 회전합니다.',
    codePreview: 'turn_right()',
    commandType: 'turn_right',
  },
  {
    id: 'wait',
    name: 'Wait',
    category: 'Utility',
    cost: 5,
    description: '1초 동안 기다립니다.',
    codePreview: 'wait(1)',
    commandType: 'wait',
  },
  {
    id: 'plant_wheat',
    name: 'Plant Wheat',
    category: 'Farming',
    cost: 5,
    description: '현재 칸에 밀을 심습니다.',
    codePreview: 'plant("wheat")',
    commandType: 'plant_wheat',
  },
  {
    id: 'harvest',
    name: 'Harvest',
    category: 'Farming',
    cost: 6,
    description: '현재 칸의 작물을 수확합니다.',
    codePreview: 'harvest()',
    commandType: 'harvest',
  },
  {
    id: 'repeat_5',
    name: 'Repeat 5',
    category: 'Control',
    cost: 30,
    description: '안쪽 블록을 5번 반복 실행합니다.',
    codePreview: 'for i in range(5):',
    commandType: 'repeat',
    repeatCount: 5,
    hasChildren: true,
  },
  {
    id: 'if_crop_ready',
    name: 'If Crop Ready',
    category: 'Control',
    cost: 25,
    description: '현재 칸의 작물이 다 자랐을 때만 안쪽 블록을 실행합니다.',
    codePreview: 'if crop_ready():',
    commandType: 'if',
    hasChildren: true,
    conditionType: 'crop_ready',
  },
  {
    id: 'add_land',
    name: '땅 추가',
    category: 'Upgrade',
    cost: 50,
    costGrowth: 1.45,
    repeatable: true,
    description: '현재 칸 옆에 땅을 1칸 추가합니다.',
    codePreview: 'add_land()',
    shopEffect: 'add_land',
  },
  {
    id: 'add_drone',
    name: '드론 추가',
    category: 'Upgrade',
    cost: 100,
    costGrowth: 1.55,
    repeatable: true,
    description: '드론을 추가로 생성합니다.',
    codePreview: 'add_drone()',
    shopEffect: 'add_drone',
  },
];

export const FREE_BLOCK_IDS = ['move', 'turn_left', 'turn_right'];

export function getBlockDefinition(blockId) {
  return BLOCK_DEFINITIONS.find((block) => block.id === blockId);
}
